### ISSUE TITLE
Option to drop adjacent-tile buffering for point features

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/planetiler-openmaptiles#102]
The metrics in openmaptiles/openmaptiles#1574 suggests that we can make significant tile size improvements by removing the adjacent-tile buffering for point features.  There are some use cases that still need the tile buffering, so this should be a command-line switch.

**Comment by msbarry** [comment]
One other consideration is if a layer uses label grid filtering/ranking we need a minimum buffer size during the process step. In that case we can apply the smaller buffer during postProcess
