### ISSUE TITLE
hide3d flag is not set to "outline" buildings

### ISSUE THREAD

**Issue by adjourn** [openmaptiles/planetiler-openmaptiles#108]
I'm not entirely sure how it's supposed to work..
* Is the `outline` relation automatically set by OSM backend? I don't have any evidence to believe that
* Does this profile assume that `outline` relation is always defined? Almost never the case
* Logic is just not implemented yet to automatically discover `outline` relations? See my comment

I did double-check multiple buildings that consist of parts and are missing `hide3d` flag (I've never seen the flag on any of the buildings in tens of hours of working/exploring output) - requirements are met: building parts are all inside the building (or share outer-wall nodes) and the entire building is covered by parts. So I can only assume that current implementation requires manually set relations in OMS to apply `hide3d` flag.

```java
// Building.java:process
Boolean hide3d = null;
var relations = element.source().relationInfo(BuildingRelationInfo.class);
for (var relation : relations) {
  if ("outline".equals(relation.role())) {
    hide3d = true;
    break;
  }
}
```

**Comment by adjourn** [comment]
From [wiki](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings):
> When a building has any [building:part](https://wiki.openstreetmap.org/wiki/Key:building:part)=* areas, the building outline is not considered for 3D rendering[[1]](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings#cite_note-1).

This is what confuses me, I'm not sure what's the assumption of this library: should this be handled by vector tile generator and the logic is just missing or should everyone just duct tape some slow JavaScript spatial logic to their (Maplibre) application?

**Comment by adjourn** [comment]
From [wiki](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings):
> When a building has any [building:part](https://wiki.openstreetmap.org/wiki/Key:building:part)=* areas, the building outline is not considered for 3D rendering[[1]](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings#cite_note-1).

This is what confuses me, I'm not sure what's the stance of this library: should this be handled by vector tile generator and the logic is just missing or should everyone just duct tape some slow JavaScript spatial logic to their (Maplibre) application?

**Comment by msbarry** [comment]
Thanks for pointing this out - this is meant to replicate logic from the openmaptiles/openmaptiles repo:

https://github.com/openmaptiles/openmaptiles/blob/9de3ff39216880fa56630bcb7a98b0faa3deaee1/layers/building/building.sql#L37

If we think this is wrong in openmaptiles, we should probably fix it there then apply that same change to this repo based on the outcome of that.

**Comment by adjourn** [comment]
Correct, now that I checked it, I see the same issue in MapTiler maps as well..
Pan the camera around ,you can see the z-fighting between "outline" and part geometry:
https://www.maptiler.com/maps/#style=streets-v2&lang=en&mode=2d&position=17.62/39.954382/-75.169874/144.70/47.3
Versus Mapbox that handles it: https://labs.mapbox.com/standard-style/#17.62/39.954382/-75.169874/144.7/43

Just out of curiousity.. From Planetiler architecture POV, is this hard to pull off? Probably not the best place to start learning Java.. I've already heavily modified the master version boundaries, places, languages, house numbers, etc but I feel like this might be too much for me. My first hunch is a lot of looping in `Building.java:postProcess`.

**Comment by adjourn** [comment]
Thanks for pointing that out.
I didn't realise that it's a 1:1 replication, was assuming that it's just based on that and can be approved upon.

Maybe it's worth to consider adding some kind of utility class/method to `planetiler` then.
Could be useful and improve a lot of 3d maps since most of them have this "bug".
