### ISSUE TITLE
route_1, route_2, etc. sometimes contains duplicates

### ISSUE THREAD

**Issue by jameswestman** [openmaptiles/planetiler-openmaptiles#115]
The route keys sometimes contain duplicates. For example, at https://maps.jwestman.net/#14.11/37.64493/-98.21414, there's a highway that is part of both eastbound and westbound route relations, so it gets each ref twice.

Can probably be solved by just collecting all the refs into a list and then deduplicating it.

**Comment by msbarry** [comment]
There's also #95 - I wonder if the logic should just be to collect the routes, sort/distinct then add `route_n` tags up to however many there are even if it's more than 5. What do you think @ZeLonewolf ?

**Comment by ZeLonewolf** [comment]
> There's also #95 - I wonder if the logic should just be to collect the routes, sort/distinct then add `route_n` tags up to however many there are even if it's more than 5. What do you think @ZeLonewolf ?

I agree with this approach, with the caveat that a style author might want a lower limit, like 2 or 3, depending on what they care about cartographically.  I see no value in keeping duplicate route_n tags and consider it a bug (and I've fixed it in OMT in openmaptiles/openmaptiles#1361.

**Comment by msbarry** [comment]
Fixed this in #117 - cc/ @phanecak-maptiler you shouldn't need to port over https://github.com/openmaptiles/openmaptiles/pull/1361 as part of the 3.15 upgrade
