### ISSUE TITLE
Move regenerate-openmaptiles script from planetiler repo

### ISSUE THREAD

**Issue by msbarry** [openmaptiles/planetiler-openmaptiles#14]
We should copy this script over so you can run it in this repo to update the code that gets generated from openmaptiles yaml files:

https://github.com/onthegomap/planetiler/blob/232834e73523f018e2659e9ee3c1575826908686/scripts/regenerate-openmaptiles.sh#L1-L20

There's probably also a github action you want to copy to make sure that regenerate works fine on each commit:

https://github.com/onthegomap/planetiler/blob/232834e73523f018e2659e9ee3c1575826908686/.github/workflows/maven.yml#L63-L78

**Comment by phanecak-maptiler** [comment]
This was already dine in:
* https://github.com/onthegomap/planetiler/pull/312
* https://github.com/openmaptiles/planetiler-openmaptiles/pull/19

Hence closing this.
