### ISSUE TITLE
[Help] Place minzooms not being used all of the time

### ISSUE THREAD

**Issue by four43** [openmaptiles/planetiler-openmaptiles#171]
I am trying to generate a set of tiles that has city names at lower zoom levels so more are visible when the map is zoomed out further. I can't seem to get some of these features to show up before certain zoom levels. It seems I can get some at zoom 0, then another batch at zoom 5, 7, etc. Even if I change `minzoom = 0` is there another place to look where that data is selected for generation?

I was looking here: https://github.com/openmaptiles/planetiler-openmaptiles/blob/main/src/main/java/org/openmaptiles/layers/Place.java#L346

This is definitely a help/discussion question, not an issue.

Thanks a lot!

**Comment by phanecak-maptiler** [comment]
There is also "label grid" (see https://github.com/openmaptiles/planetiler-openmaptiles/blob/main/src/main/java/org/openmaptiles/layers/Place.java#L357,L358 ) and a limit (see https://github.com/openmaptiles/planetiler-openmaptiles/blob/main/src/main/java/org/openmaptiles/layers/Place.java#L361 and https://github.com/openmaptiles/planetiler-openmaptiles/blob/main/src/main/java/org/openmaptiles/layers/Place.java#L113)

Which means that for each zoom level from Z0 to Z12 a tile is split into areas of 128x128 pixel and feature count is kept within a limits set in `LABEL_GRID_LIMITS` by discarding some features.

**Comment by four43** [comment]
Hey thanks for the point in the right direction! That was very helpful. I'll give those a look.
