### ISSUE TITLE
Please add a customization guide

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/planetiler-openmaptiles#39]
The [Generating Custom Vector Tiles](https://github.com/onthegomap/planetiler#generating-custom-vector-tiles) section in planetiler's README.md says:

> fork https://github.com/openmaptiles/planetiler-openmaptiles make changes there

Please add a guide of how to make such changes in a fork of this repository.

As a trating point, it would be great if the guide will cover two basic use-cases for making changes in such a fork:

1. Add fields to an existing layer, potentially with some filter
2. Add a new layer

**Comment by msbarry** [comment]
@zstadler took a stab at this in #41 - what do you think?

**Comment by zstadler** [comment]
@msbarry The description of adding a layer looks good!

I've suggested describing a specific change to an existing layer - adding fields. The current description is too general for the novice programmer:

> If you want to customize existing layers in OpenMapTiles, then fork this repo and change the logic for the appropriate
class from the [layers package](src/main/java/org/openmaptiles/layers).

To me it reads like "fork the repository and change the class of the layer", but how? I don't even know where is the list of current fields and what changes in the logic are needed for each newly added field.

I would also like to suggest that adding fields will be described first, as it seems like a smaller change to the scheme, at least from a user's perspective.

**Comment by msbarry** [comment]
Made a quick update to add examples of adding an attribute and a custom layer, check out https://github.com/msbarry/planetiler-openmaptiles/blob/customizing/README.md#customizing.

I don't think this is the place to fully document planetiler's API, but I'm hoping that examples could point people in the right direction.

**Comment by zstadler** [comment]
@msbarry Awesome!
This is exactly what I had hoped to see, now with actual code!
