### ISSUE TITLE
[BUG] name:xx missing in transportation_name

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/planetiler-openmaptiles#58]
Moved from onthegomap/planetiler#419
Unblocks ZeLonewolf/openstreetmap-americana#618
CC @zstadler

Internationalized `name:xx` names are missing from roads in the transportation_name layer.

The following object show internationalized names in omt-tools:
![image](https://user-images.githubusercontent.com/3254090/208552068-ecbca63a-3ef4-4606-b968-0db0e334f1fe.png)

Same location in my planetiler server ([link](https://6ug7hetxl9.execute-api.us-east-2.amazonaws.com/data/v3/#14/32.08566/34.78968))
![image](https://user-images.githubusercontent.com/3254090/208553427-fb5d9511-18dc-45e3-9483-de2591843ae2.png)

**Comment by 1ec5** [comment]
To keep these line references from getting outdated as the repository changes, here are some permalinks to relevant parts of the code:

https://github.com/openmaptiles/planetiler-openmaptiles/blob/6317d82ec9dff205cd2de90d020433592009e807/src/main/java/org/openmaptiles/layers/TransportationName.java#L127 https://github.com/openmaptiles/planetiler-openmaptiles/blob/6317d82ec9dff205cd2de90d020433592009e807/src/main/java/org/openmaptiles/layers/TransportationName.java#L131-L133 https://github.com/openmaptiles/planetiler-openmaptiles/blob/6317d82ec9dff205cd2de90d020433592009e807/src/main/java/org/openmaptiles/layers/TransportationName.java#L204 https://github.com/openmaptiles/planetiler-openmaptiles/blob/6317d82ec9dff205cd2de90d020433592009e807/src/main/java/org/openmaptiles/layers/TransportationName.java#L264 https://github.com/openmaptiles/planetiler-openmaptiles/blob/6317d82ec9dff205cd2de90d020433592009e807/src/main/java/org/openmaptiles/layers/TransportationName.java#L312 https://github.com/openmaptiles/planetiler-openmaptiles/blob/6317d82ec9dff205cd2de90d020433592009e807/src/main/java/org/openmaptiles/layers/TransportationName.java#L327
