### ISSUE TITLE
Specify zoom levels

### ISSUE THREAD

**Issue by slutske22** [openmaptiles/planetiler-openmaptiles#92]
Thank you for this great tool.

Is there a way to specify (via command line or in code), that I only want to generate tiles for a specific zoom range?  I.e. if I want to start at z4, and only generate up to z12?  I don't see this as an option anywhere?  Perhaps I am misunderstanding or missing something in the docs?

**Comment by msbarry** [comment]
Yep! Try `--minzoom=4 --maxzoom=12`
