### ISSUE TITLE
Configurable concurrency limit

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/planetiler-openmaptiles#95]
Currently, the limit on simultaneous concurrencies (`route_N` attributes in the `transportation_name` layer), is six.  However, we've identified cases as large as eight in ZeLonewolf/openstreetmap-americana#894.

Instead, planetiler-openmaptiles should have a configurable limit on route concurrencies, so a style author can determine the longest shield snake length that makes cartographic sense to render.

**Comment by msbarry** [comment]
Should we just dynamically generate the `route_n` tags up to however many there are on a way?
